In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [0]:
#this section will be on the 28 features excel file

In [0]:
df=pd.read_excel("28 Features.xlsx")
#df.head(5)

In [0]:
#df.columns

In [0]:
df['tumor_grade'].unique()

array(['G4', 'G2', 'G3', 'G1'], dtype=object)

In [0]:
#df.isnull().sum()

In [0]:
#for i in df.columns:
 # print(df[i].unique())


In [0]:
df.replace({'[not]':0,'[Unknown]':1,'[not ]':0,"Yes, History of Synchronous/Bilateral Malignancy":'Yes','Yes, History of Prior Malignancy':'Yes'},inplace=True)

In [0]:
for column in df.columns:
  if column not in ["lymph_nodes_examined_count","death_days_to","radiation_therapy_started_days_to","new_tumor_event_dx_days_to"] :
    n=len(df[column].unique())
    l=[1+i for i in range(n)]
    map_dict={}
    l2=df[column].unique()
    for j in range(len(l2)):
      map_dict[l2[j]]=l[j]
    df[column].replace(map_dict,inplace=True)
    print(map_dict)
df.head(10)

{'Stage IV': 1, 'Stage III': 2, 'Stage I': 3, 'Stage II': 4}
{'NO': 1, 'YES': 2, 0: 3}
{'PALLIATIVE': 1, 0: 2, 'PROGRESSION': 3, 'OTHER, SPECIFY IN NOTES': 4, 'ADJUVANT': 5, 'RECURRENCE': 6}
{'Right': 1, 'Left': 2}
{'Normal': 1, 'Low': 2, 0: 3, 'Elevated': 4}
{'WITH TUMOR': 1, 'TUMOR FREE': 2, 0: 3, 1: 4}
{'NO': 1, 0: 2, 'YES': 3}
{'T3b': 1, 'T3a': 2, 'T1b': 3, 'T1a': 4, 'T2': 5, 'T2a': 6, 'T4': 7, 'T1': 8, 'T2b': 9, 'T3c': 10}
{'M1': 1, 'M0': 2, 'MX': 3}
{'Dead': 1, 'Alive': 2, 0: 3}
{'Normal': 1, 'Low': 2, 'Elevated': 3, 0: 4}
{'BP': 1, 'B0': 2, 'CJ': 3, 'DV': 4, 'CW': 5, 'CZ': 6, 'B8': 7, 'G6': 8}
{0: 1, 1: 2, 2: 3, 3: 4}
{'Elevated': 1, 'Normal': 2, 0: 3, 'Low': 4}
{'G4': 1, 'G2': 2, 'G3': 3, 'G1': 4}
{'WITH TUMOR': 1, 'TUMOR FREE': 2, 0: 3}
{'Sunitinib': 1, 0: 2, 'xeloda': 3, 'Sutent (Sunitinib)': 4, 'Sorafenib - Nexavar': 5, 'Bevacizumab': 6, 'Temsirolimus': 7, 'proleukin (IL-2)': 8, 'Gemcitabine': 9, 'Avastin': 10, 'Sutent': 11, 'Axitnib': 12, 'Oncophage': 13, 'Sorafenib': 14, '

ajcc_pathologic_tumor_stage  new_tumor_event_surgery_met  \
0                            1                            1   
1                            1                            1   
2                            1                            1   
3                            1                            1   
4                            1                            1   
5                            1                            1   
6                            1                            2   
7                            1                            2   
8                            1                            2   
9                            2                            2   

   therapy_regimen_drug  laterality  platelet_count  \
0                     1           1               1   
1                     1           1               1   
2                     1           1               1   
3                     1           1               1   
4                     1           1               1   
5                     1           1               1   
6                     1           1               1   
7                     1           1               1   
8                     1           1               1   
9                     2           1               1   

   lymph_nodes_examined_count  tumor_status_followup  \
0                          10                      1   
1                          10                      1   
2                          10                      1   
3                          10                      1   
4                          10                      1   
5                          10                      1   
6                          10                      1   
7                          10                      1   
8                          10                      1   
9                           2                      1   

   pharmaceutical_tx_ongoing_indicator  ajcc_tumor_pathologic_pt  \
0                                    1                         1   
1                                    1                         1   
2                                    1                         1   
3                                    1                         1   
4                                    1                         1   
5                                    1                         1   
6                                    1                         1   
7                                    1                         1   
8                                    1                         1   
9                                    2                         1   

   ajcc_metastasis_pathologic_pm  ...  race  death_days_to  \
0                              1  ...     1            344   
1                              1  ...     1            344   
2                              1  ...     1            344   
3                              1  ...     1            344   
4                              1  ...     1            344   
5                              1  ...     1            344   
6                              1  ...     1            344   
7                              1  ...     1            344   
8                              1  ...     1            344   
9                              2  ...     1              0   

   vital_status_followup.1  pharmaceutical_therapy_type  \
0                        1                            1   
1                        1                            1   
2                        1                            1   
3                        1                            1   
4                        1                            1   
5                        1                            1   
6                        1                            1   
7                        1                            1   
8                        1                            1   
9                        2                            2   

   n

In [0]:
for i in df.columns:
  print(str(i)+"--->",df[i].unique())


ajcc_pathologic_tumor_stage---> [1 2 3 4]
new_tumor_event_surgery_met---> [1 2 3]
therapy_regimen_drug---> [1 2 3 4 5 6]
laterality---> [1 2]
platelet_count---> [1 2 3 4]
lymph_nodes_examined_count---> [10  2  0 17  1  9  5 16 14  4 19  3 21  6 11  8  7 13 15 25]
tumor_status_followup---> [1 2 3 4]
pharmaceutical_tx_ongoing_indicator---> [1 2 3]
ajcc_tumor_pathologic_pt---> [ 1  2  3  4  5  6  7  8  9 10]
ajcc_metastasis_pathologic_pm---> [1 2 3]
vital_status_followup---> [1 2 3]
serum_calcium_level---> [1 2 3 4]
tissue_source_site---> [1 2 3 4 5 6 7 8]
ecog_score_final---> [1 2 3 4]
white_cell_count---> [1 2 3 4]
tumor_grade---> [1 2 3 4]
tumor_status_patient---> [1 2 3]
pharmaceutical_therapy_drug_name---> [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
race---> [1 2 3 4]
death_days_to---> [ 344    0 1625  563  446  822 1317  320  572   93  313  164  552 1714
  701  679 1343  166

In [0]:
df["lymph_nodes_examined_count"].unique()

array([10,  2,  0, 17,  1,  9,  5, 16, 14,  4, 19,  3, 21,  6, 11,  8,  7,
       13, 15, 25], dtype=int64)

In [0]:
y=df['tumor_grade']
df.drop('tumor_grade',axis=1,inplace=True)

In [0]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
X_train,X_test,y_train,y_test=train_test_split(df,y,random_state=42,test_size=0.2)
for column in ["lymph_nodes_examined_count","death_days_to","radiation_therapy_started_days_to","new_tumor_event_dx_days_to"]:
  X_train[column]=np.log(np.absolute(X_train[column])+1)
  X_test[column]=np.log(np.absolute(X_test[column])+1)
#X_train=StandardScaler().fit_transform(X_train)
#X_test=StandardScaler().fit_transform(X_test)

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [0]:
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
knn=KNeighborsClassifier(n_neighbors=5)
clf = svm.SVC(kernel='linear', C=4)
scores = cross_val_score(knn, X_train, y_train, cv=5)
print(scores)

[0.65060241 0.62962963 0.65       0.6875     0.67088608]


D:\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:657: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)


In [0]:
knn.fit(X_train,y_train)
y_pred=knn.predict(X_test)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))#Accuracy score of Using K Nearest Neighbours

0.6732673267326733


In [0]:
scores = cross_val_score(clf, X_train, y_train,cv=5)
print(scores)
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)
print(accuracy_score(y_test,y_pred))#Accuracy score for Using SVM

D:\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:657: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)


[0.62650602 0.67901235 0.75       0.7125     0.70886076]
0.6435643564356436


In [0]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()
scores = cross_val_score(dtc, X_train, y_train, cv=3)
print(scores)

[0.65693431 0.65413534 0.72932331]


D:\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:657: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)


In [0]:
dtc.fit(X_train,y_train)
y_pred=dtc.predict(X_test)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.7623762376237624


In [0]:
from sklearn.ensemble import RandomForestClassifier
rfc= RandomForestClassifier(max_depth=5)
scores = cross_val_score(rfc, X_train, y_train, cv=3)
print(scores)

[0.70072993 0.69172932 0.66917293]


D:\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:657: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)
D:\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [0]:
rfc.fit(X_train,y_train)
y_pred=dtc.predict(X_test)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.7623762376237624


D:\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [0]:
from sklearn.ensemble import GradientBoostingClassifier

gbc=GradientBoostingClassifier(n_estimators=200,max_depth=4,verbose=True)
cross_val_score(gbc,X_train,y_train,cv=3)

D:\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:657: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)


      Iter       Train Loss   Remaining Time 
         1         262.2956            1.41s
         2         238.4816            1.13s
         3         218.5977            0.95s
         4         201.2775            1.09s
         5         186.9695            1.14s
         6         174.1773            1.11s
         7         162.9378            1.21s
         8         152.6442            1.24s
         9         143.3703            1.24s
        10         135.4520            1.27s
        20          90.5873            1.10s
        30          64.6766            1.11s
        40          50.9626            1.04s
        50          41.2313            0.94s
        60          35.6261            0.89s
        70          30.9594            0.81s
        80          26.5425            0.77s
        90          22.8009            0.70s
       100          19.9099            0.63s
       200           7.3829            0.00s
      Iter       Train Loss   Remaining Time 
        

array([0.68613139, 0.7443609 , 0.80451128])

In [0]:
gbc.fit(X_train,y_train)

      Iter       Train Loss   Remaining Time 
         1         396.8449            1.43s
         2         360.2073            1.42s
         3         331.0139            1.35s
         4         304.9413            1.38s
         5         283.3779            1.50s
         6         265.7997            1.50s
         7         249.8889            1.55s
         8         236.3070            1.59s
         9         224.6850            1.61s
        10         213.6521            1.44s
        20         151.6598            1.47s
        30         122.2834            1.45s
        40         104.2953            1.32s
        50          90.6912            1.24s
        60          78.7155            1.14s
        70          67.7162            1.05s
        80          58.0070            0.96s
        90          49.1918            0.91s
       100          43.8028            0.82s
       200          18.7853            0.00s


GradientBoostingClassifier(criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=4,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=200,
                           n_iter_no_change=None, presort='auto',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=True,
                           warm_start=False)

In [0]:
y_pred=gbc.predict(X_test)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.7623762376237624


In [0]:
#this section will have the result of 33 features

In [0]:
y.unique()

array([1, 2, 3, 4], dtype=int64)