In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [0]:
#this section will be on the 28 features excel file

In [0]:
df=pd.read_excel("33 Features.xlsx")
#df.head(5)

In [0]:
#df.columns

In [0]:
#df['tumor_grade'].unique()

In [0]:
#df.isnull().sum()

In [0]:
#for i in df.columns:
  #print(str(i)+"--->",df[i].unique())


In [0]:
df.replace({'[not]':0,'[Unknown]':1,'[not ]':0,"Yes, History of Synchronous/Bilateral Malignancy":'Yes','Yes, History of Prior Malignancy':'Yes'},inplace=True)

In [0]:
for i in df.columns:
  print(str(i)+"--->",df[i].unique())


gender---> ['FEMALE' 'MALE']
history_neoadjuvant_treatment---> ['No' 'Yes']
ajcc_nodes_pathologic_pn---> ['N0' 'NX' 'N1']
treatment_outcome_first_course---> [0 'Partial Remission/Response' 'Progressive Disease'
 'Complete Remission/Response' 'Stable Disease']
lymph_nodes_examined_positive---> [0 2 1]
ajcc_pathologic_tumor_stage---> ['Stage IV' 'Stage III' 'Stage I' 'Stage II']
new_tumor_event_surgery_met---> ['NO' 'YES' 0]
therapy_regimen_drug---> ['PALLIATIVE' 0 'PROGRESSION' 'OTHER, SPECIFY IN NOTES' 'ADJUVANT'
 'RECURRENCE']
laterality---> ['Right' 'Left']
platelet_count---> ['Normal' 'Low' 0 'Elevated']
lymph_nodes_examined_count---> [10  2  0 17  1  9  5 16 14  4 19  3 21  6 11  8  7 13 15 25]
tumor_status_followup---> ['WITH TUMOR' 'TUMOR FREE' 0 1]
pharmaceutical_tx_ongoing_indicator---> ['NO' 0 'YES']
ajcc_tumor_pathologic_pt---> ['T3b' 'T3a' 'T1b' 'T1a' 'T2' 'T2a' 'T4' 'T1' 'T2b' 'T3c']
ajcc_metastasis_pathologic_pm---> ['M1' 'M0' 'MX']
vital_status_followup---> ['Dead' 'Alive

In [0]:
for column in df.columns:
  if column not in ["lymph_nodes_examined_count","death_days_to","radiation_therapy_started_days_to","new_tumor_event_dx_days_to"] :
    n=len(df[column].unique())
    l=[1+i for i in range(n)]
    map_dict={}
    l2=df[column].unique()
    for j in range(len(l2)):
      map_dict[l2[j]]=l[j]
    df[column].replace(map_dict,inplace=True)
    print(n,l2,map_dict)
df.head(10)

2 ['FEMALE' 'MALE'] {'FEMALE': 1, 'MALE': 2}
2 ['No' 'Yes'] {'No': 1, 'Yes': 2}
3 ['N0' 'NX' 'N1'] {'N0': 1, 'NX': 2, 'N1': 3}
5 [0 'Partial Remission/Response' 'Progressive Disease'
 'Complete Remission/Response' 'Stable Disease'] {0: 1, 'Partial Remission/Response': 2, 'Progressive Disease': 3, 'Complete Remission/Response': 4, 'Stable Disease': 5}
3 [0 2 1] {0: 1, 2: 2, 1: 3}
4 ['Stage IV' 'Stage III' 'Stage I' 'Stage II'] {'Stage IV': 1, 'Stage III': 2, 'Stage I': 3, 'Stage II': 4}
3 ['NO' 'YES' 0] {'NO': 1, 'YES': 2, 0: 3}
6 ['PALLIATIVE' 0 'PROGRESSION' 'OTHER, SPECIFY IN NOTES' 'ADJUVANT'
 'RECURRENCE'] {'PALLIATIVE': 1, 0: 2, 'PROGRESSION': 3, 'OTHER, SPECIFY IN NOTES': 4, 'ADJUVANT': 5, 'RECURRENCE': 6}
2 ['Right' 'Left'] {'Right': 1, 'Left': 2}
4 ['Normal' 'Low' 0 'Elevated'] {'Normal': 1, 'Low': 2, 0: 3, 'Elevated': 4}
4 ['WITH TUMOR' 'TUMOR FREE' 0 1] {'WITH TUMOR': 1, 'TUMOR FREE': 2, 0: 3, 1: 4}
3 ['NO' 0 'YES'] {'NO': 1, 0: 2, 'YES': 3}
10 ['T3b' 'T3a' 'T1b' 'T1a' 'T2' '

gender  history_neoadjuvant_treatment  ajcc_nodes_pathologic_pn  \
0       1                              1                         1   
1       1                              1                         1   
2       1                              1                         1   
3       1                              1                         1   
4       1                              1                         1   
5       1                              1                         1   
6       1                              1                         1   
7       1                              1                         1   
8       1                              1                         1   
9       1                              1                         1   

   treatment_outcome_first_course  lymph_nodes_examined_positive  \
0                               1                              1   
1                               1                              1   
2                               1                              1   
3                               1                              1   
4                               1                              1   
5                               1                              1   
6                               1                              1   
7                               1                              1   
8                               1                              1   
9                               1                              1   

   ajcc_pathologic_tumor_stage  new_tumor_event_surgery_met  \
0                            1                            1   
1                            1                            1   
2                            1                            1   
3                            1                            1   
4                            1                            1   
5                            1                            1   
6                            1                            2   
7                            1                            2   
8                            1                            2   
9                            2                            2   

   therapy_regimen_drug  laterality  platelet_count  ...  race  death_days_to  \
0                     1           1               1  ...     1            344   
1                     1           1               1  ...     1            344   
2                     1           1               1  ...     1            344   
3                     1           1               1  ...     1            344   
4                     1           1               1  ...     1            344   
5                     1           1               1  ...     1            344   
6                     1           1               1  ...     1            344   
7                     1           1               1  ...     1            344   
8                     1           1               1  ...     1            344   
9                     2           1               1  ...     1              0   

   vital_status_followup.1  pharmaceutical_therapy_type  \
0                        1                            1   
1                        1                            1   
2                        1                            1   
3                        1                            1   
4                        1                            1   
5                        1                            1   
6                        1                            1   
7                        1                            1   
8                        1                            1   
9                        2                            2   

   new_tumor_event_dx_days_to  ethnicity  hemoglobin_level  \
0                          13          1                 1   
1                          13          1                 1   
2                          13          1                 1   

In [0]:
df["lymph_nodes_examined_count"].unique()

array([10,  2,  0, 17,  1,  9,  5, 16, 14,  4, 19,  3, 21,  6, 11,  8,  7,
       13, 15, 25], dtype=int64)

In [0]:
y=df['tumor_grade']
df.drop('tumor_grade',axis=1,inplace=True)

In [0]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
X_train,X_test,y_train,y_test=train_test_split(df,y,random_state=42,test_size=0.2)
for column in X_train:#["lymph_nodes_examined_count","death_days_to","radiation_therapy_started_days_to","new_tumor_event_dx_days_to"]:
  X_train[column]=np.log(np.absolute(X_train[column])+1)
for column in X_test:
  X_test[column]=np.log(np.absolute(X_test[column])+1)

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys


In [0]:
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
knn=KNeighborsClassifier(n_neighbors=5)
clf = svm.SVC(kernel='linear', C=4)
scores = cross_val_score(knn, X_train, y_train, cv=5)
print(scores)

[0.59036145 0.62962963 0.725      0.75       0.55696203]


D:\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:657: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)


In [0]:
knn.fit(X_train,y_train)
y_pred=knn.predict(X_test)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))#Accuracy score of Using K Nearest Neighbours

0.6435643564356436


In [0]:
scores = cross_val_score(clf, X_train, y_train,cv=5)
print(scores)
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)
print(accuracy_score(y_test,y_pred))#Accuracy score for Using SVM

D:\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:657: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)


[0.60240964 0.71604938 0.8125     0.75       0.6835443 ]
0.693069306930693


In [0]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()
scores = cross_val_score(dtc, X_train, y_train, cv=3)
print(scores)

[0.68613139 0.68421053 0.73684211]


D:\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:657: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)


In [0]:
dtc.fit(X_train,y_train)
y_pred=dtc.predict(X_test)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.7821782178217822


In [0]:
from sklearn.ensemble import RandomForestClassifier
rfc= RandomForestClassifier(max_depth=5)
scores = cross_val_score(rfc, X_train, y_train, cv=3)
print(scores)

[0.65693431 0.63157895 0.69924812]


D:\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:657: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)
D:\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [0]:
rfc.fit(X_train,y_train)
y_pred=dtc.predict(X_test)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.7821782178217822


D:\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [0]:
from sklearn.ensemble import GradientBoostingClassifier

gbc=GradientBoostingClassifier(n_estimators=200,max_depth=4,verbose=True)
cross_val_score(gbc,X_train,y_train,cv=3)

D:\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:657: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)


      Iter       Train Loss   Remaining Time 
         1         262.3394            0.97s
         2         239.5088            0.88s
         3         218.4601            0.97s
         4         200.8213            1.24s
         5         185.8708            1.33s
         6         173.5015            1.38s
         7         162.2207            1.33s
         8         152.0340            1.40s
         9         143.3191            1.39s
        10         134.8058            1.39s
        20          90.1377            1.26s
        30          64.4428            1.22s
        40          50.0562            1.11s
        50          39.6127            1.03s
        60          31.7241            0.95s
        70          25.8959            0.89s
        80          21.0675            0.82s
        90          17.5628            0.75s
       100          14.2003            0.68s
       200           3.6588            0.00s
      Iter       Train Loss   Remaining Time 
        

array([0.70072993, 0.79699248, 0.83458647])

In [0]:
gbc.fit(X_train,y_train)

      Iter       Train Loss   Remaining Time 
         1         396.7763            1.60s
         2         359.8549            1.87s
         3         329.6732            1.77s
         4         303.4880            1.80s
         5         282.1312            1.84s
         6         264.4700            1.85s
         7         247.8846            1.88s
         8         234.5824            1.87s
         9         222.8092            1.83s
        10         211.5700            1.79s
        20         146.7066            1.64s
        30         116.1460            1.56s
        40          94.1382            1.43s
        50          77.3605            1.35s
        60          65.1797            1.25s
        70          55.2273            1.16s
        80          46.5374            1.07s
        90          40.7396            0.98s
       100          35.6440            0.88s
       200          13.7843            0.00s


GradientBoostingClassifier(criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=4,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=200,
                           n_iter_no_change=None, presort='auto',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=True,
                           warm_start=False)

In [0]:
y_pred=gbc.predict(X_test)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.8217821782178217


In [0]:
#this section will have the result of 33 features

In [0]:
y.unique()

array([1, 2, 3, 4], dtype=int64)