In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [0]:
#this section will be on the 28 features excel file

In [0]:
df=pd.read_excel("39 Features.xlsx")
#df.head(5)

In [0]:
#df.columns

In [0]:
#df['tumor_grade'].unique()

In [0]:
#df.isnull().sum()

In [0]:
#for i in df.columns:
  #print(str(i)+"--->",df[i].unique())


In [0]:
df.replace({'[not]':0,'[Unknown]':1,'[not ]':0,"Yes, History of Synchronous/Bilateral Malignancy":'Yes','Yes, History of Prior Malignancy':'Yes'},inplace=True)

In [0]:
for i in df.columns:
  print(str(i)+"--->",df[i].unique())


radiation_therapy_started_days_to---> [ 263  271   61  481  165    0  385  422   69  -72   21  603  227  298
  153  457 1755 1787 1903 1174 2070 1534  119  748  994  234    6  685
  702  324  477  600  483  169  301  729  842]
tumor_grade---> ['G4' 'G2' 'G3' 'G1']
laterality---> ['Right' 'Left']
prospective_collection---> ['NO' 0 'YES']
gender---> ['FEMALE' 'MALE']
race---> ['WHITE' 'BLACK OR AFRICAN AMERICAN' 0 'ASIAN']
ethnicity---> ['NOT HISPANIC OR LATINO' 0 'HISPANIC OR LATINO']
history_other_malignancy---> ['No' 'Yes']
history_neoadjuvant_treatment---> ['No' 'Yes']
lymph_nodes_examined_count---> [10  2  0 17  1  9  5 16 14  4 19  3 21  6 11  8  7 13 15 25]
lymph_nodes_examined_positive---> [0 2 1]
ajcc_tumor_pathologic_pt---> ['T3b' 'T3a' 'T1b' 'T1a' 'T2' 'T2a' 'T4' 'T1' 'T2b' 'T3c']
ajcc_nodes_pathologic_pn---> ['N0' 'NX' 'N1']
ajcc_metastasis_pathologic_pm---> ['M1' 'M0' 'MX']
ajcc_pathologic_tumor_stage---> ['Stage IV' 'Stage III' 'Stage I' 'Stage II']
vital_status_followup---

In [0]:
for column in df.columns:
  if column not in ["lymph_nodes_examined_count","radiation_adjuvant_fractions_total","death_days_to","radiation_therapy_started_days_to","new_tumor_event_dx_days_to","radiation_total_dose","regimen_number"] :
    n=len(df[column].unique())
    l=[1+i for i in range(n)]
    map_dict={}
    l2=df[column].unique()
    for j in range(len(l2)):
      map_dict[l2[j]]=l[j]
    df[column].replace(map_dict,inplace=True)
    print(n,l2,map_dict)
df.head(10)

4 ['G4' 'G2' 'G3' 'G1'] {'G4': 1, 'G2': 2, 'G3': 3, 'G1': 4}
2 ['Right' 'Left'] {'Right': 1, 'Left': 2}
3 ['NO' 0 'YES'] {'NO': 1, 0: 2, 'YES': 3}
2 ['FEMALE' 'MALE'] {'FEMALE': 1, 'MALE': 2}
4 ['WHITE' 'BLACK OR AFRICAN AMERICAN' 0 'ASIAN'] {'WHITE': 1, 'BLACK OR AFRICAN AMERICAN': 2, 0: 3, 'ASIAN': 4}
3 ['NOT HISPANIC OR LATINO' 0 'HISPANIC OR LATINO'] {'NOT HISPANIC OR LATINO': 1, 0: 2, 'HISPANIC OR LATINO': 3}
2 ['No' 'Yes'] {'No': 1, 'Yes': 2}
2 ['No' 'Yes'] {'No': 1, 'Yes': 2}
3 [0 2 1] {0: 1, 2: 2, 1: 3}
10 ['T3b' 'T3a' 'T1b' 'T1a' 'T2' 'T2a' 'T4' 'T1' 'T2b' 'T3c'] {'T3b': 1, 'T3a': 2, 'T1b': 3, 'T1a': 4, 'T2': 5, 'T2a': 6, 'T4': 7, 'T1': 8, 'T2b': 9, 'T3c': 10}
3 ['N0' 'NX' 'N1'] {'N0': 1, 'NX': 2, 'N1': 3}
3 ['M1' 'M0' 'MX'] {'M1': 1, 'M0': 2, 'MX': 3}
4 ['Stage IV' 'Stage III' 'Stage I' 'Stage II'] {'Stage IV': 1, 'Stage III': 2, 'Stage I': 3, 'Stage II': 4}
3 ['Dead' 'Alive' 0] {'Dead': 1, 'Alive': 2, 0: 3}
3 ['WITH TUMOR' 'TUMOR FREE' 0] {'WITH TUMOR': 1, 'TUMOR FREE': 2, 0

radiation_therapy_started_days_to  tumor_grade  laterality  \
0                                263            1           1   
1                                271            1           1   
2                                 61            1           1   
3                                263            1           1   
4                                271            1           1   
5                                 61            1           1   
6                                263            1           1   
7                                271            1           1   
8                                 61            1           1   
9                                481            2           1   

   prospective_collection  gender  race  ethnicity  history_other_malignancy  \
0                       1       1     1          1                         1   
1                       1       1     1          1                         1   
2                       1       1     1          1                         1   
3                       1       1     1          1                         1   
4                       1       1     1          1                         1   
5                       1       1     1          1                         1   
6                       1       1     1          1                         1   
7                       1       1     1          1                         1   
8                       1       1     1          1                         1   
9                       1       1     1          1                         1   

   history_neoadjuvant_treatment  lymph_nodes_examined_count  ...  \
0                              1                          10  ...   
1                              1                          10  ...   
2                              1                          10  ...   
3                              1                          10  ...   
4                              1                          10  ...   
5                              1                          10  ...   
6                              1                          10  ...   
7                              1                          10  ...   
8                              1                          10  ...   
9                              1                           2  ...   

   route_of_administration  therapy_regimen_drug  \
0                        1                     1   
1                        1                     1   
2                        1                     1   
3                        1                     1   
4                        1                     1   
5                        1                     1   
6                        1                     1   
7                        1                     1   
8                        1                     1   
9                        2                     2   

   treatment_outcome_first_course  tumor_status_followup  death_days_to  \
0                               1                      1            344   
1                               1                      1            344   
2                               1                      1            344   
3                               1                      1            344   
4                               1                      1            344   
5                               1                      1            344   
6                               1                      1            344   
7                               1                      1            344   
8                               1                      1            344   
9                               1                      1              0   

   new_tumor_event_dx_days_to  new_tumor_event_surgery_met  \
0                          13                            1   
1                          13                            1   
2                          13                            1   

In [0]:
df["lymph_nodes_examined_count"].unique()

array([10,  2,  0, 17,  1,  9,  5, 16, 14,  4, 19,  3, 21,  6, 11,  8,  7,
       13, 15, 25], dtype=int64)

In [0]:
y=df['tumor_grade']
df.drop('tumor_grade',axis=1,inplace=True)

In [0]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
X_train,X_test,y_train,y_test=train_test_split(df,y,random_state=42,test_size=0.2)
for column in ["lymph_nodes_examined_count","radiation_adjuvant_fractions_total","death_days_to","radiation_therapy_started_days_to","new_tumor_event_dx_days_to","radiation_total_dose","regimen_number"]:
  X_train[column]=np.log(np.absolute(X_train[column])+1)
  X_test[column]=np.log(np.absolute(X_test[column])+1)

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [0]:
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
knn=KNeighborsClassifier(n_neighbors=5)
clf = svm.SVC(kernel='linear', C=4)
scores = cross_val_score(knn, X_train, y_train, cv=5)
print(scores)

[0.56626506 0.59259259 0.6        0.7125     0.56962025]


D:\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:657: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)


In [0]:
knn.fit(X_train,y_train)
y_pred=knn.predict(X_test)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))#Accuracy score of Using K Nearest Neighbours

0.594059405940594


In [0]:
scores = cross_val_score(clf, X_train, y_train,cv=5)
print(scores)
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)
print(accuracy_score(y_test,y_pred))#Accuracy score for Using SVM

D:\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:657: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)


[0.63855422 0.71604938 0.775      0.7375     0.65822785]
0.7128712871287128


In [0]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()
scores = cross_val_score(dtc, X_train, y_train, cv=3)
print(scores)

[0.64963504 0.69172932 0.72180451]


D:\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:657: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)


In [0]:
dtc.fit(X_train,y_train)
y_pred=dtc.predict(X_test)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.7524752475247525


In [0]:
from sklearn.ensemble import RandomForestClassifier
rfc= RandomForestClassifier(max_depth=5)
scores = cross_val_score(rfc, X_train, y_train, cv=3)
print(scores)

D:\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:657: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)


[0.68613139 0.65413534 0.69924812]


D:\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
D:\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [0]:
rfc.fit(X_train,y_train)
y_pred=dtc.predict(X_test)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.7524752475247525


D:\Anaconda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [0]:
from sklearn.ensemble import GradientBoostingClassifier

gbc=GradientBoostingClassifier(n_estimators=200,max_depth=4,verbose=True)
cross_val_score(gbc,X_train,y_train,cv=3)

D:\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:657: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)


      Iter       Train Loss   Remaining Time 
         1         261.9452            0.80s
         2         238.8024            1.22s
         3         217.9153            1.18s
         4         200.3745            1.22s
         5         185.5232            1.17s
         6         173.2195            1.25s
         7         162.0010            1.37s
         8         152.5328            1.33s
         9         142.9792            1.41s
        10         135.0203            1.41s
        20          88.0868            1.22s
        30          63.1058            1.27s
        40          48.7158            1.18s
        50          40.2793            1.06s
        60          33.9808            1.01s
        70          28.6192            0.93s
        80          24.1087            0.85s
        90          19.7833            0.78s
       100          16.2205            0.71s
       200           3.5473            0.00s
      Iter       Train Loss   Remaining Time 
        

array([0.67153285, 0.76691729, 0.83458647])

In [0]:
gbc.fit(X_train,y_train)

      Iter       Train Loss   Remaining Time 
         1         396.4595            2.20s
         2         359.7084            1.80s
         3         329.1067            1.70s
         4         302.7300            1.78s
         5         281.0608            1.89s
         6         263.0719            2.00s
         7         247.1793            1.93s
         8         233.7181            1.96s
         9         220.7229            2.02s
        10         210.5224            1.83s
        20         146.6938            1.81s
        30         116.9604            1.68s
        40          97.5680            1.58s
        50          83.0594            1.44s
        60          68.2042            1.34s
        70          58.0932            1.23s
        80          50.1350            1.14s
        90          43.6434            1.03s
       100          38.9025            0.94s
       200          12.7220            0.00s


GradientBoostingClassifier(criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=4,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=200,
                           n_iter_no_change=None, presort='auto',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=True,
                           warm_start=False)

In [0]:
y_pred=gbc.predict(X_test)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.8118811881188119


In [0]:
#this section will have the result of 33 features

In [0]:
y.unique()

array([1, 2, 3, 4], dtype=int64)